name: tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    env:
      API_KEY: ${{ secrets.DID_API_KEY }}
      PYTHONPATH: ${{ github.workspace }}/examples

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r examples/requirements.txt
          pip install pytest pytest-cov

      - name: Run pytests
        run: |
          pytest --cov=examples --cov-report=term-missing
